export const Endpoints = {
    "TODO":"/todos",
    "TEST":"/gura",
    "LOGIN":"/login",
    "REGISTER":"/register",
    "ACCOUNT":"/account",
    "FREELANCERS":"/freelancers",
    "FREELANCER":"/freelancer",
    "JOBS":"/jobs",
    "JOB":"/job",
    "OFFER":"/offer",
    "OFFER_STATUS":"/offer-status",
    "PORTFOLIO":"/portfolio",
    "PROJECTS":"/projects",
    "PROJECT":"/project",
    "RECRUITER": "/recruiter",
    "SKILL":"/skills",
    "TOPUP":"/payment/topup",

}